version: "3"
services:
  lighttpd:
    build: $PWD/lighttpd/
    volumes:
      - compile:/mnt/out
      - ${BINARIES_DIR}:/mnt/in
      - log:/mnt/log
    ports:
      - ${HTTPD_PORT}:80

  gcc:
    build: $PWD/gcc/
    volumes:
      - compile:/mnt/in
      - ${BINARIES_DIR}:/mnt/out
      - log:/mnt/log
volumes:
  compile:
  log:
